### ISSUE TITLE
UnicodeEncodeError is thrown because of windows cmd  'gbk' codec problem

### ISSUE THREAD

**Issue by VijayQin** [VijayQin/DMHY-spider#5]
When downloading page(19:35 Aug 02 2016)
https://share.dmhy.org/topics/view/438777_160727_TV_Vol_2_320K.html
a UnicodeEncodeError is thrown
complete error message is following:
已完成：186/204
[2FTraceback (most recent call last):
  File "DMHY_DataBase.py", line 357, in <module>
    DataBase.start_requests()
  File "DMHY_DataBase.py", line 172, in start_requests
    self.parse_item(update_list[i], con)
  File "DMHY_DataBase.py", line 218, in parse_item
    print u"[姝ｅ湪涓嬭浇] " + item_title
UnicodeEncodeError: 'gbk' codec can't encode character u'\u30fb' in position 28: illegal multibyte sequence
![image](https://cloud.githubusercontent.com/assets/6880815/18006774/e952a31c-6bd3-11e6-9c7b-adb1fe011886.png)

**Comment by VijayQin** [comment]
It's fixed at 2206 Aug 08 16
By adding try……except……
for example:
        try:
            print u"[正在下载] " + item_title
        except Exception, e:
            print (u"[正在下载] " + item_title).encode("GBK", 'ignore')
