### ISSUE TITLE
sqlite3 ProgrammingError is thrown while downloading the animation from[2016-07-01,2016-08-27]

### ISSUE THREAD

**Issue by VijayQin** [VijayQin/DMHY-spider#7]
sqlite3 ProgrammingError is thrown while downloading the animation from[2016-07-01,2016-08-27]
The error message is 
Traceback (most recent call last):
  File "DMHY_DataBase.py", line 420, in <module>
    DataBase.start_requests()
  File "DMHY_DataBase.py", line 223, in start_requests
    cu.execute(insert_sql, d)
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
It seems like the exception is thrown while inserting into database.
![image](https://cloud.githubusercontent.com/assets/6880815/18038446/d93d754e-6dca-11e6-92ed-524fdc5582fc.png)

**Comment by VijayQin** [comment]
This is caused by property attach encode error, and it has been fixed in version 2.0.0.
